---
version: v1
plugins:
  - name: openapiv2
    out: ./protos/generated/data-node/swagger
    opt:
      - logtostderr=true
      - grpc_api_configuration=protos/sources/data-node/grpc-rest-bindings.yml
  - name: openapiv2
    out: ./protos/generated/fury/swagger
    opt:
      - logtostderr=true
      - grpc_api_configuration=protos/sources/fury/grpc-rest-bindings.yml
  - name: openapiv2
    out: ./protos/generated/blockexplorer/swagger
    opt:
      - logtostderr=true
      - grpc_api_configuration=protos/sources/blockexplorer/grpc-rest-bindings.yml
  - name: doc
    out: ./protos/generated/grpc
    opt:
      - json
      - proto.json
    strategy: all
